#!/data/data/com.termux/files/usr/bin/sh
pkg remove termux-display-nightly -y
pkg remove termux-x11-nightly -y
pkg -i x11-repo
dpkg -i /data/data/com.termux/files/home/xkeyboard-config_2.45_all.deb
dpkg -i /data/data/com.termux/files/home/termux-x11-nightly-1.03.10-0-all.deb
chmod +x $PREFIX/bin/termux-x11*
