#!/data/data/com.termux/files/usr/bin/sh
pkg remove termux-display-nightly -y
pkg remove termux-x11-nightly -y
if [[ -z $(dpkg -l | grep xkeyboard-config) ]]; then
    dpkg -i /data/data/com.termux/files/home/xkeyboard-config_2.45_all.deb
fi
dpkg -i /data/data/com.termux/files/home/termux-x11-nightly-1.03.10-0-all.deb
chmod +x /data/data/com.termux/files/usr/bin/startxserver
chmod +x /data/data/com.termux/files/usr/bin/stopserver
chmod +x /data/data/com.termux/files/usrbin/termux-x11*
